#!/bin/bash

# SGE OPTIONS
#$ -S /bin/bash
#$ -q short.q
#$ -N quantify
#$ -V
#$ -cwd
#$ -b n
#$ -pe smp 16
#$ -l mem_requested=8G,tmp_requested=150G,tmpfree=150G

CELLRANGER_PATH=/share/ScratchGeneral/annsen/pipelines/cellranger-3.0.2
export PATH=$CELLRANGER_PATH:$PATH
source $CELLRANGER_PATH/sourceme.bash

# Set up arguments for run
INPUT_CSV=${SGE_O_WORKDIR}/aggr.csv
ID=H9_RPE_AGGR
OUTPUT_DIR=/share/ScratchGeneral/annsen/data/experimental_data/CLEAN/RPE_scRNA_AgedStudy

cd $OUTPUT_DIR

# Run Cell Ranger
cellranger aggr --id=${ID} --csv=$INPUT_CSV --normalize=mapped
